- name: Load kernel module 
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter
    - overlay

- name: Add sysctl conf
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/kubernetes.conf
    state: present
  with_items:
    - name: net.bridge.bridge-nf-call-iptables
      value: "1"
    - name: net.bridge.bridge-nf-call-ip6tables
      value: "1"
    - name: net.ipv4.ip_forward
      value: "1"

- name: Reload sysctl settings
  command: sysctl --system

- name: Wait for dpkg lock to be released
  command: "bash -c 'while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 2; done'"
  changed_when: false

- name: Remove broken dpkg update file
  command: rm -rf /var/lib/dpkg/updates
  ignore_errors: true

- name: Ensure dpkg is configured
  command: dpkg --configure -a
  ignore_errors: true

- name: Full upgrade the system
  apt:
    upgrade: full
    update_cache: yes
    autoremove: yes
    
- name: Reboot the server after upgrade
  reboot:
    msg: "Reboot initiated by Ansible after full upgrade"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 10
    post_reboot_delay: 30