- name: Load kernel module 
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter
    - overlay

- name: Add sysctl conf
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/kubernetes.conf
    state: present
  with_items:
    - name: net.bridge.bridge-nf-call-iptables
      value: "1"
    - name: net.bridge.bridge-nf-call-ip6tables
      value: "1"
    - name: net.ipv4.ip_forward
      value: "1"

- name: Reload sysctl settings
  command: sysctl --system

- name: Remove apt lists lock
  command: rm /var/lib/apt/lists/lock
  ignore_errors: true 

- name: Remove apt archives lock
  command: rm /var/cache/apt/archives/lock
  ignore_errors: true 

- name: Full upgrade the system
  apt:
    upgrade: full
    update_cache: yes
    autoremove: yes

- name: Reboot the server after upgrade
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible after full upgrade"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 10
    post_reboot_delay: 30