- name: Load kernel module 
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter
    - overlay

- name: Add sysctl conf
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/kubernetes.conf
    state: present
  with_items:
    - name: net.bridge.bridge-nf-call-iptables
      value: "1"
    - name: net.bridge.bridge-nf-call-ip6tables
      value: "1"
    - name: net.ipv4.ip_forward
      value: "1"

- name: Reload sysctl settings
  command: sysctl --system

- name: Remove apt lists lock
  command: rm /var/lib/apt/lists/lock
  ignore_errors: true 

- name: Remove apt archives lock
  command: rm /var/cache/apt/archives/lock
  ignore_errors: true 

- name: Remove dpkg lock if it exists
  command: rm -f /var/lib/dpkg/lock-frontend
  ignore_errors: true

- name: Remove dpkg lock file (legacy)
  command: rm -f /var/lib/dpkg/lock
  ignore_errors: true

- name: Remove broken dpkg update file
  command: rm -f /var/lib/dpkg/updates/0000
  ignore_errors: true

- name: Ensure dpkg is configured
  command: dpkg --configure -a
  ignore_errors: true

- name: Check if dpkg is configured successfully
  command: dpkg --configure -a
  register: dpkg_status
  until: dpkg_status.rc == 0
  retries: 5
  delay: 10

- name: Full upgrade the system
  apt:
    upgrade: full
    update_cache: yes
    autoremove: yes
  when: dpkg_status.rc == 0

- name: Reboot the server after upgrade
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible after full upgrade"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 10
    post_reboot_delay: 30