apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: storage-configuration
spec:
  itemPath: "vaults/Kubernetes/items/minio_storage-configuration"

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: storage-user
spec:
  itemPath: "vaults/Kubernetes/items/minio_storage-user"