apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
stringData:
  config.env: |-
    export MINIO_ROOT_USER="{{ .Values.secret.configuration.user }}"
    export MINIO_ROOT_PASSWORD="{{ .Values.secret.configuration.password }}"
    export MINIO_STORAGE_CLASS_STANDARD="{{ .Values.secret.configuration.storageClassStandard }}"
    export MINIO_BROWSER="{{ .Values.secret.configuration.browser }}"
type: Opaque
---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: {{ .Values.secret.user.accessKey }}
  CONSOLE_SECRET_KEY: {{ .Values.secret.user.secretKey }}
kind: Secret
metadata:
  name: storage-user
type: Opaque