apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: navidrome
  namespace: flux-system
spec:
  interval: 10m
  path: "./flux/clusters/natsume/apps/navidrome"
  prune: true
  wait: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: cert-manager-config
  - name: prometheus-operator-crd
  - name: traefik
