apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tempo
  namespace: flux-system
spec:
  interval: 10m
  path: "./flux/clusters/natsume/apps/tempo"
  prune: true
  wait: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: cert-manager
  - name: external-dns
  - name: external-secrets
  - name: traefik
