apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tetragon-policies
  namespace: flux-system
spec:
  interval: 10m
  path: "./flux/clusters/natsume/apps/tetragon-policies"
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
  - name: tetragon
  sourceRef:
    kind: GitRepository
    name: flux-system
