apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mc-mirror-cronjob
  namespace: mc-mirror-cronjob
spec:
  interval: 10m
  releaseName: mc-mirror-cronjob
  targetNamespace: mc-mirror-cronjob
  install:
    createNamespace: false
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: ./charts/mc-mirror-cronjob
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1h
  values:
    externalSecret:
      name: mc-mirror-cronjob-secrets
    cronjob:
      schedule: "0 0 * * *" 
