apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-auth-token
  namespace: renovate-operator
spec:
  refreshInterval: 30m
  target:
    name: renovate-secret
    template:
      type: Opaque
      engineVersion: v2
      data:
        GITHUB_COM_TOKEN: "{{ .token }}"
        RENOVATE_TOKEN: "{{ .token }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: github-auth-token
