tempo:
  extraArgs:
    config.expand-env: true
  extraEnvFrom:
    - secretRef:
        name: minio-secrets
  storage:
    trace:
      backend: s3
      s3:
        access_key: "${S3_ACCESS_KEY_ID}"
        secret_key: "${S3_SECRET_ACCESS_KEY}"
        bucket: "tempo-traces"
        endpoint: "minio.str08.net"
        region: "minio-kkg-1"
        forcepathstyle: true
      wal:
        path: /var/tempo/wal
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

persistence:
  enabled: true
  size: 10Gi

serviceMonitor:
  enabled: true
