---
- name: Update apt cache (equivalent to apt-get update)
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present

- name: Create directory for apt keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add CRI-O repository key
  shell:
    cmd: > 
      curl -fsSL https://pkgs.k8s.io/addons:/cri-o:/stable:/{{ crio_version }}/deb/Release.key |
      gpg --yes --dearmor -o /etc/apt/keyrings/cri-o-apt-keyring.gpg

- name: Add CRI-O repository
  shell:
    cmd: > 
      echo 'deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/stable:/{{ crio_version }}/deb/ /' |
      tee /etc/apt/sources.list.d/cri-o.list

- name: Install CRI-O
  apt:
    name: "cri-o"
    state: present
    update_cache: yes

- name: Start and enable CRI-O service
  systemd:
    name: crio
    enabled: yes
    state: started
    
- name: Configure CRI-O runtime settings in /etc/crio/crio.conf
  blockinfile:
    path: /etc/crio/crio.conf
    block: |
      [crio.runtime]
      conmon_cgroup = "pod"
      cgroup_manager = "cgroupfs"

      [crio.image]
      pause_image = "registry.k8s.io/pause:3.6"
    create: yes
    marker: ""

- name: Restart CRI-O service
  systemd:
    name: crio
    state: restarted
    enabled: yes