- name: Install UFW
  become: true
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: Set UFW default policies
  become: true
  community.general.ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }

- name: Allow required ports
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: "{{ frp_host_ufw_allow_ports }}"

- name: Enable UFW
  become: true
  community.general.ufw:
    state: enabled
