apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: tempo
spec:
  interval: 10m
  releaseName: tempo
  targetNamespace: tempo
  install:
    createNamespace: false
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: tempo
      version: 2.2.3
      sourceRef:
        kind: HelmRepository
        name: tempo-repo
        namespace: tempo
      interval: 1h
  values:
    serviceMonitor:
      enabled: true
    persistence:
      enabled: true
      size: 20Gi
    tempo:
      reportingEnabled: false
      retention: 336h
      extraArgs:
        config.expand-env: "true"
      extraEnvFrom:
      - secretRef:
          name: r2-o11y-secret
      server:
        http_listen_port: 3200
      storage:
        trace:
          backend: s3
          s3:
            endpoint: ${S3_ENDPOINT}
            bucket: tempo-traces
            access_key: ${S3_ACCESS_KEY_ID}
            secret_key: ${S3_SECRET_ACCESS_KEY}
            region: auto
            insecure: false
            forcepathstyle: true
          wal:
            path: /var/tempo/wal
      metricsGenerator:
        enabled: true
        processor:
          local_blocks:
            flush_to_storage: true
        storage:
          path: /var/tempo/metrics
          remote_write:
            - url: http://mimir.mimir:8080/api/v1/push
              headers:
                X-Scope-OrgID: anonymous
        traces_storage:
          path: /var/tempo/metrics-wal
      overrides:
        defaults:
          metrics_generator:
            processors:
              - local-blocks
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
            http:
              endpoint: "0.0.0.0:4318"
      resources:
        requests:
          cpu: 200m
          memory: 1Gi
        limits:
          memory: 4Gi
