repositories:
  - name: cilium
    url: https://helm.cilium.io/
  - name: 1password
    url: https://1password.github.io/connect-helm-charts/
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: cilium
    namespace: kube-system
    chart: cilium/cilium
    version: 1.19.0
    values:
      - values/cilium.gotmpl
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-n"
          - "kube-system"
          - "-f"
          - "manifests/cilium/default-pool.yaml"
      - events: ["preuninstall"]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-n"
          - "kube-system"
          - "-f"
          - "manifests/cilium/default-pool.yaml"
          - "--ignore-not-found=true"

  - name: connect
    namespace: 1password
    createNamespace: true
    chart: 1password/connect
    version: 2.3.0
    needs:
      - kube-system/cilium
    values:
      - values/1password-connect.gotmpl

  - name: argocd
    namespace: argocd
    createNamespace: true
    chart: argo/argo-cd
    version: 9.4.1
    needs:
      - kube-system/cilium
    values:
      - values/argocd.gotmpl
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-n"
          - "argocd"
          - "-f"
          - "manifests/argocd/root-app.yaml"
      - events: ["preuninstall"]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-n"
          - "argocd"
          - "-f"
          - "manifests/argocd/root-app.yaml"
          - "--ignore-not-found=true"
