repositories:
  - name: cilium
    url: https://helm.cilium.io/
  - name: nfs-subdir-external-provisioner
    url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  - name: 1password
    url: https://1password.github.io/connect-helm-charts/
  - name: jetstack
    url: quay.io/jetstack/charts
    oci: true
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/
  - name: tailscale
    url: https://pkgs.tailscale.com/helmcharts
  - name: traefik
    url: https://traefik.github.io/charts
  - name: cloudflare
    url: https://cloudflare.github.io/helm-charts
  - name: uptime-kuma
    url: https://helm.irsigler.cloud
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: vm
    url: https://victoriametrics.github.io/helm-charts/
  - name: minio
    url: https://operator.min.io

releases:
  - name: cilium
    namespace: kube-system
    chart: cilium/cilium
    version: 1.18.0
    values:
      - values/cilium.gotmpl
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-n"
          - "kube-system"
          - "-f"
          - "manifests/cilium/default-pool.yaml"
      - events: ["preuninstall"]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-n"
          - "kube-system"
          - "-f"
          - "manifests/cilium/default-pool.yaml"
          - "--ignore-not-found=true"
  
  - name: nfs-subdir-external-provisioner
    namespace: kube-system
    chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    version: 4.0.18
    values:
      - values/nfs-subdir-external-provisioner.gotmpl

  - name: connect
    namespace: 1password
    chart: 1password/connect
    version: 2.0.2
    createNamespace: true
    values:
      - values/1password-connect.gotmpl
    set:
      - name: connect.credentials
        file: 1password-credentials.json

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.18.2
    createNamespace: true
    needs:
      - 1password/connect
    set:
      - name: crds.enabled
        value: true
    hooks:
      - events: [postsync]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-n"
          - "cert-manager"
          - "-f"
          - "manifests/cert-manager/clusterissuer.yaml"
      - events: [preuninstall]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-n"
          - "cert-manager"
          - "-f"
          - "manifests/cert-manager/clusterissuer.yaml"
          - "--ignore-not-found=true"

  - name: external-dns
    namespace: external-dns
    chart: external-dns/external-dns
    version: 1.17.0
    createNamespace: true
    needs:
      - 1password/connect
    values:
      - values/external-dns.gotmpl
    hooks:
      - events: [postsync]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-n"
          - "external-dns"
          - "-f"
          - "manifests/external-dns/onepassworditem.yaml"
      - events: [preuninstall]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-n"
          - "external-dns"
          - "-f"
          - "manifests/external-dns/onepassworditem.yaml"
          - "--ignore-not-found=true"

  - name: tailscale-operator
    namespace: tailscale
    chart: tailscale/tailscale-operator
    version: 1.86.2
    createNamespace: true
    needs:
      - 1password/connect
    hooks:
      - events: [postsync]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-n"
          - "tailscale"
          - "-f"
          - "manifests/tailscale-operator/onepassworditem.yaml"
      - events: [preuninstall]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-n"
          - "tailscale"
          - "-f"
          - "manifests/tailscale-operator/onepassworditem.yaml"
          - "--ignore-not-found=true"

  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    version: 37.0.0
    createNamespace: true
    needs:
      - cert-manager/cert-manager
      - external-dns/external-dns
    values:
      - values/traefik.gotmpl
    hooks:
      - events: [postsync]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-n"
          - "traefik"
          - "-f"
          - "manifests/traefik/certificate.yaml"
      - events: [preuninstall]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-n"
          - "traefik"
          - "-f"
          - "manifests/traefik/certificate.yaml"
          - "--ignore-not-found=true"

  - name: traefik-tailscale
    namespace: traefik-tailscale
    chart: traefik/traefik
    version: 37.0.0
    createNamespace: true
    needs:
      - cert-manager/cert-manager
      - external-dns/external-dns
    values:
      - values/traefik-tailscale.gotmpl
    hooks:
      - events: [postsync]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-n"
          - "traefik-tailscale"
          - "-f"
          - "manifests/traefik-tailscale/certificate.yaml"
      - events: [preuninstall]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-n"
          - "traefik-tailscale"
          - "-f"
          - "manifests/traefik-tailscale/certificate.yaml"
          - "--ignore-not-found=true"

  - name: cloudflare-tunnel
    namespace: cloudflare
    chart: cloudflare/cloudflare-tunnel
    version: 0.3.2
    createNamespace: true
    needs:
      - 1password/connect
    values:
      - values/cloudflare-tunnel.gotmpl
    hooks:
      - events: [postsync]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-n"
          - "cloudflare"
          - "-f"
          - "manifests/cloudflare-tunnel/onepassworditem.yaml"
      - events: [preuninstall]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-n"
          - "cloudflare"
          - "-f"
          - "manifests/cloudflare-tunnel/onepassworditem.yaml"
          - "--ignore-not-found=true"

  - name: uptime-kuma
    namespace: uptime-kuma
    chart: uptime-kuma/uptime-kuma
    version: 2.22.0
    createNamespace: true
    values:
      - values/uptime-kuma.gotmpl

  - name: grafana
    namespace: grafana
    chart: grafana/grafana
    version: 9.3.1
    createNamespace: true
    needs:
      - traefik/traefik
      - traefik-tailscale/traefik-tailscale
      - cert-manager/cert-manager
      - external-dns/external-dns
    values:
      - values/grafana.gotmpl
    hooks:
      - events: [postsync]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-n"
          - "grafana"
          - "-f"
          - "manifests/grafana/ingress-tailscale.yaml"
      - events: [preuninstall]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-n"
          - "grafana"
          - "-f"
          - "manifests/grafana/ingress-tailscale.yaml"
          - "--ignore-not-found=true"

  - name: vmcluster
    namespace: victoria-metrics
    chart: vm/victoria-metrics-cluster
    version: 0.27.1
    createNamespace: true
    needs:
      - traefik/traefik
      - traefik-tailscale/traefik-tailscale
      - cert-manager/cert-manager
      - external-dns/external-dns
    values:
      - values/victoria-metrics-cluster.gotmpl
    hooks:
      - events: [postsync]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-n"
          - "victoria-metrics"
          - "-f"
          - "manifests/victoriametrics/ingress-tailscale.yaml"
      - events: [preuninstall]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-n"
          - "victoria-metrics"
          - "-f"
          - "manifests/victoriametrics/ingress-tailscale.yaml"
          - "--ignore-not-found=true"

  - name: minio-operator
    namespace: minio-operator
    chart: minio/operator
    version: 7.1.1
    createNamespace: true

  - name: minio-tenant
    namespace: minio-tenant
    chart: minio/tenant
    version: 7.1.1
    createNamespace: true
    needs:
      - minio-operator/minio-operator
      - 1password/connect
    values:
      - values/minio-tenant.gotmpl
    hooks:
      - events: [postsync]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-n"
          - "minio-tenant"
          - "-f"
          - "manifests/minio-tenant/onepassworditem.yaml"
      - events: [preuninstall]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-n"
          - "minio-tenant"
          - "-f"
          - "manifests/minio-tenant/onepassworditem.yaml"
          - "--ignore-not-found=true"