repositories:
  - name: cilium
    url: https://helm.cilium.io/
  - name: 1password
    url: https://1password.github.io/connect-helm-charts/
  - name: jetstack
    url: quay.io/jetstack/charts
    oci: true
  - name: nfs-subdir-external-provisioner
    url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/
  - name: strrl
    url: https://helm.strrl.dev
  - name: traefik
    url: https://traefik.github.io/charts
  - name: minio
    url: https://operator.min.io
  - name: uptime-kuma
    url: https://helm.irsigler.cloud
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: soli0222
    url: https://soli0222.github.io/helm-charts

releases:
  - name: cilium
    namespace: kube-system
    chart: cilium/cilium
    version: 1.18.1
    values:
      - values/cilium.gotmpl
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-n"
          - "kube-system"
          - "-f"
          - "manifests/cilium/default-pool.yaml"
      - events: ["preuninstall"]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-n"
          - "kube-system"
          - "-f"
          - "manifests/cilium/default-pool.yaml"
          - "--ignore-not-found=true"

  - name: connect
    namespace: 1password
    chart: 1password/connect
    version: 2.0.2
    needs:
      - kube-system/cilium
    createNamespace: true
    values:
      - values/1password-connect.gotmpl

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.18.2
    needs:
      - kube-system/cilium
    createNamespace: true
    set:
      - name: crds.enabled
        value: true
    hooks:
      - events: [postsync]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-n"
          - "cert-manager"
          - "-f"
          - "manifests/cert-manager/clusterissuer.yaml"
      - events: [preuninstall]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-n"
          - "cert-manager"
          - "-f"
          - "manifests/cert-manager/clusterissuer.yaml"
          - "--ignore-not-found=true"
  
  - name: nfs-subdir-external-provisioner
    namespace: kube-system
    chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    version: 4.0.18
    needs:
      - kube-system/cilium
    values:
      - values/nfs-subdir-external-provisioner.gotmpl

  - name: minio-operator
    namespace: minio-operator
    chart: minio/operator
    version: 7.1.1
    needs:
      - kube-system/cilium
    createNamespace: true

  - name: external-dns
    namespace: external-dns
    chart: external-dns/external-dns
    version: 1.18.0
    needs:
      - 1password/connect
    createNamespace: true
    values:
      - values/external-dns.gotmpl
    hooks:
      - events: [postsync]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-n"
          - "external-dns"
          - "-f"
          - "manifests/external-dns/onepassworditem.yaml"
      - events: [preuninstall]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-n"
          - "external-dns"
          - "-f"
          - "manifests/external-dns/onepassworditem.yaml"
          - "--ignore-not-found=true"

  - name: cloudflare-tunnel-ingress-controller
    namespace: cloudflare-tunnel-ingress-controller
    chart: strrl/cloudflare-tunnel-ingress-controller
    version: 0.0.18
    needs:
      - 1password/connect
    createNamespace: true
    values:
      - values/cloudflare-tunnel-ingress-controller.gotmpl
    hooks:
      - events: [postsync]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-n"
          - "cloudflare-tunnel-ingress-controller"
          - "-f"
          - "manifests/cloudflare-tunnel-ingress-controller/onepassworditem.yaml"
      - events: [preuninstall]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-n"
          - "cloudflare-tunnel-ingress-controller"
          - "-f"
          - "manifests/cloudflare-tunnel-ingress-controller/onepassworditem.yaml"
          - "--ignore-not-found=true"

  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    version: 37.0.0
    createNamespace: true
    needs:
      - cert-manager/cert-manager
      - external-dns/external-dns
    values:
      - values/traefik.gotmpl
    hooks:
      - events: [postsync]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-n"
          - "traefik"
          - "-f"
          - "manifests/traefik/certificate.yaml"
      - events: [preuninstall]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-n"
          - "traefik"
          - "-f"
          - "manifests/traefik/certificate.yaml"
          - "--ignore-not-found=true"

  - name: minio-tenant
    namespace: minio-tenant
    chart: minio/tenant
    version: 7.1.1
    createNamespace: true
    needs:
      - kube-system/nfs-subdir-external-provisioner
      - traefik/traefik
      - minio-operator/minio-operator
    values:
      - values/minio-tenant.gotmpl
    hooks:
      - events: [postsync]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-n"
          - "minio-tenant"
          - "-f"
          - "manifests/minio-tenant/onepassworditem.yaml"
      - events: [preuninstall]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-n"
          - "minio-tenant"
          - "-f"
          - "manifests/minio-tenant/onepassworditem.yaml"
          - "--ignore-not-found=true"

  - name: uptime-kuma
    namespace: uptime-kuma
    chart: uptime-kuma/uptime-kuma
    version: 2.22.0
    needs:
      - kube-system/nfs-subdir-external-provisioner
      - cert-manager/cert-manager
      - external-dns/external-dns
      - cloudflare-tunnel-ingress-controller/cloudflare-tunnel-ingress-controller
    createNamespace: true
    values:
      - values/uptime-kuma.gotmpl

  - name: grafana
    namespace: grafana
    chart: grafana/grafana
    version: 9.3.2
    createNamespace: true
    needs:
      - kube-system/nfs-subdir-external-provisioner
      - traefik/traefik
      - cloudflare-tunnel-ingress-controller/cloudflare-tunnel-ingress-controller
    values:
      - values/grafana.gotmpl

  - name: mimir
    namespace: mimir
    chart: grafana/mimir-distributed
    version: 5.8.0
    createNamespace: true
    needs:
      - minio-tenant/minio-tenant
      - cloudflare-tunnel-ingress-controller/cloudflare-tunnel-ingress-controller
    values:
      - values/mimir.gotmpl
    hooks:
      - events: [postsync]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-n"
          - "mimir"
          - "-f"
          - "manifests/mimir/onepassworditem.yaml"
      - events: [preuninstall]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-n"
          - "mimir"
          - "-f"
          - "manifests/mimir/onepassworditem.yaml"
          - "--ignore-not-found=true"

  - name: loki
    namespace: loki
    chart: grafana/loki
    version: 6.36.1
    createNamespace: true
    needs:
      - minio-tenant/minio-tenant
      - cloudflare-tunnel-ingress-controller/cloudflare-tunnel-ingress-controller
    values:
      - values/loki.gotmpl
    hooks:
      - events: [postsync]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-n"
          - "loki"
          - "-f"
          - "manifests/loki/onepassworditem.yaml"
      - events: [preuninstall]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-n"
          - "loki"
          - "-f"
          - "manifests/loki/onepassworditem.yaml"
          - "--ignore-not-found=true"

  - name: alloy
    namespace: alloy
    chart: grafana/alloy
    version: 1.2.1
    createNamespace: true
    needs:
      - mimir/mimir
      - loki/loki
    values:
      - values/alloy.gotmpl

  - name: daypassed-bot
    namespace: daypassed-bot
    chart: soli0222/daypassed-bot
    version: 0.1.0
    createNamespace: true
    needs:
      - 1password/connect
    values:
      - values/dayspassed-bot.gotmpl

  # - name: flow-sight
  #   namespace: flow-sight
  #   chart: soli0222/flow-sight
  #   version: 1.1.0
  #   createNamespace: true
  #   needs:
  #     - traefik/traefik
  #   values:
  #     - values/flow-sight.gotmpl

  - name: mc-mirror-cronjob
    namespace: mc-mirror-cronjob
    chart: soli0222/mc-mirror-cronjob
    version: 0.2.0
    createNamespace: true
    needs:
      - minio-tenant/minio-tenant
    values:
      - values/mc-mirror-cronjob.gotmpl

  - name: mk-stream
    namespace: mk-stream
    chart: soli0222/mk-stream
    version: 1.0.0
    createNamespace: true
    needs:
      - 1password/connect
    values:
      - values/mk-stream.gotmpl

  - name: navidrome
    namespace: navidrome
    chart: soli0222/navidrome
    version: 1.0.0
    createNamespace: true
    needs:
      - kube-system/nfs-subdir-external-provisioner
      - cloudflare-tunnel-ingress-controller/cloudflare-tunnel-ingress-controller
    values:
      - values/navidrome.gotmpl

  - name: note-tweet-connector
    namespace: note-tweet-connector
    chart: soli0222/note-tweet-connector
    version: 0.3.0
    createNamespace: true
    needs:
      - cloudflare-tunnel-ingress-controller/cloudflare-tunnel-ingress-controller
    values:
      - values/note-tweet-connector.gotmpl

  - name: spotify-nowplaying
    namespace: spotify-nowplaying
    chart: soli0222/spotify-nowplaying
    version: 1.0.0
    createNamespace: true
    needs:
      - cloudflare-tunnel-ingress-controller/cloudflare-tunnel-ingress-controller
    values:
      - values/spotify-nowplaying.gotmpl

  - name: subscription-manager
    namespace: subscription-manager
    chart: soli0222/subscription-manager
    version: 1.1.0
    createNamespace: true
    needs:
      - 1password/connect
    values:
      - values/subscription-manager.gotmpl

  