repositories:
  - name: cilium
    url: https://helm.cilium.io/
  - name: nfs-subdir-external-provisioner
    url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  - name: 1password
    url: https://1password.github.io/connect-helm-charts/
  - name: jetstack
    url: quay.io/jetstack/charts
    oci: true
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/
  - name: tailscale
    url: https://pkgs.tailscale.com/helmcharts

releases:
  - name: cilium
    namespace: kube-system
    chart: cilium/cilium
    version: 1.18.0
    values:
      - values/cilium.gotmpl
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "manifests/cilium/default-pool.yaml"
      - events: ["preuninstall"]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-f"
          - "manifests/cilium/default-pool.yaml"
          - "--ignore-not-found=true"
  
  - name: nfs-subdir-external-provisioner
    namespace: kube-system
    chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    version: 4.0.18
    values:
      - values/nfs-subdir-external-provisioner.gotmpl

  - name: connect
    namespace: 1password
    chart: 1password/connect
    version: 2.0.2
    createNamespace: true
    values:
      - values/1password-connect.gotmpl
    set:
      - name: connect.credentials
        file: 1password-credentials.json

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.18.2
    createNamespace: true
    needs:
      - 1password/connect
    set:
      - name: crds.enabled
        value: true
    hooks:
      - events: [postsync]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "manifests/cert-manager/clusterissuer.yaml"
      - events: [preuninstall]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-f"
          - "manifests/cert-manager/clusterissuer.yaml"
          - "--ignore-not-found=true"

  - name: external-dns
    namespace: external-dns
    chart: external-dns/external-dns
    version: 1.17.0
    createNamespace: true
    needs:
      - 1password/connect
    values:
      - values/external-dns.gotmpl
    hooks:
      - events: [postsync]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "manifests/external-dns/onepassworditem.yaml"
      - events: [preuninstall]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-f"
          - "manifests/external-dns/onepassworditem.yaml"
          - "--ignore-not-found=true"

  - name: tailscale-operator
    namespace: tailscale
    chart: tailscale/tailscale-operator
    version: 1.86.2
    createNamespace: true
    needs:
      - 1password/connect
    hooks:
      - events: [postsync]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "manifests/tailscale-operator/onepassworditem.yaml"
      - events: [preuninstall]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-f"
          - "manifests/tailscale-operator/onepassworditem.yaml"
          - "--ignore-not-found=true"