repositories:
  - name: cilium
    url: https://helm.cilium.io/
  - name: 1password
    url: https://1password.github.io/connect-helm-charts/

releases:
  - name: cilium
    namespace: kube-system
    chart: cilium/cilium
    version: 1.19.3
    values:
      - values/cilium.gotmpl

  - name: connect
    namespace: 1password
    createNamespace: true
    chart: 1password/connect
    version: 2.4.1
    values:
      - values/1password-connect.gotmpl
    needs:
      - kube-system/cilium

  - name: flux-operator
    namespace: flux-system
    createNamespace: true
    chart: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
    version: 0.48.0
    needs:
      - kube-system/cilium
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "manifests/flux/fluxinstance.yaml"
      - events: ["preuninstall"]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-f"
          - "manifests/flux/fluxinstance.yaml"
          - "--ignore-not-found=true"
