apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: oky-synology-01
provisioner: csi.san.synology.com
parameters:
  fsType: 'btrfs'
  dsm: '192.168.20.250'
  location: '/volume1'
  formatOptions: '--nodiscard'
reclaimPolicy: Retain
allowVolumeExpansion: true