apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: oky-synology-02-nfs
provisioner: csi.san.synology.com
parameters:
  protocol: "nfs"
  dsm: '192.168.20.250'
  location: '/volume1/oky-synology-02-nfs'
  mountPermissions: '0777'
  type: thin
mountOptions:
  - nfsvers=4.1
reclaimPolicy: Delete
allowVolumeExpansion: true
