- name: Install HAProxy
  apt:
    name:
      - haproxy
    state: present

- name: Copy configuration file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Ensure nonlocal bind kernel parameter is set
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    state: present
    ignoreerrors: yes

- name: Ensure HAProxy is started and enabled
  service:
    name: haproxy
    state: started
    enabled: yes