- name: Create frps configuration directory
  ansible.builtin.file:
    path: /etc/frps
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy frps configuration file
  ansible.builtin.template:
    src: frps.toml.j2
    dest: /etc/frps/frps.toml
    owner: root
    group: root
    mode: '0640'
  notify: restart frps

- name: Deploy custom 404 page
  ansible.builtin.copy:
    src: 404.html
    dest: /etc/frps/404.html
    owner: root
    group: root
    mode: '0644'

- name: Deploy frps Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /etc/frps/docker-compose.yml
    owner: root
    group: root
    mode: '0644'

- name: Pull frps Docker image
  community.docker.docker_compose_v2_pull:
    project_src: /etc/frps
    files:
      - docker-compose.yml

- name: Start frps container with Docker Compose
  community.docker.docker_compose_v2:
    project_src: /etc/frps
    files:
      - docker-compose.yml
    state: present
    recreate: auto
