---
- name: Extract major.minor version from kubernetes_version
  set_fact:
    k8s_major_minor: "{{ kubernetes_version | regex_replace('^v?([0-9]+\\.[0-9]+).*', '\\1') }}"
    
- name: Update apt cache (equivalent to apt-get update)
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present

- name: Create directory for apt keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Kubernetes repository key
  shell:
    cmd: > 
      curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ k8s_major_minor }}/deb/Release.key |
      gpg --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repository
  shell:
    cmd: > 
      echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_major_minor }}/deb/ /' |
      tee /etc/apt/sources.list.d/kubernetes.list

- name: Update apt cache (equivalent to apt-get update)
  apt:
    update_cache: yes

- name: Install Kubernetes packages (kubeadm, kubelet, kubectl)
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes
