apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: misskey-stg-cluster
  namespace: misskey-stg
spec:
  instances: 1
  imageName: ghcr.io/soli0222/pgroonga-cnpg/4.0.6-alpine:18
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: misskey_stg
      owner: misskey_stg
