apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: misskey-stg-pooler-rw
  namespace: misskey-stg
spec:
  cluster:
    name: misskey-stg-cluster
  instances: 2
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "200"
      default_pool_size: "30"
      reserve_pool_size: "10"
      reserve_pool_timeout: "3"
      server_idle_timeout: "120"
      server_lifetime: "3600"
      query_wait_timeout: "30"
  template:
    spec:
      containers: []
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  cnpg.io/poolerName: misskey-stg-pooler-rw
              topologyKey: kubernetes.io/hostname
