ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: sui.str08.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: sui.str08.net-dns01
      hosts:
        - sui.str08.net

postgresql:
  enabled: false

externalPostgres:
  host: sui-cluster-rw
  port: 5432
  database: sui
  user: sui
  existingSecret: sui-cluster-app
  existingSecretKey: password
