apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mimir.configMapName" . }}
  labels:
    {{- include "mimir.labels" . | nindent 4 }}
data:
  mimir.yaml: |
    {{- include "mimir.renderedConfig" . | nindent 4 }}
