apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- helmrepository-note-tweet-connector-repo.yaml
- helmrelease-note-tweet-connector.yaml
- onepassworditem.yaml
