apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: peertube
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/zendet/peertube-helm.git
      targetRevision: main
      path: .
      helm:
        valueFiles:
          - $values/argocd/peertube/values.yaml
    - chart: valkey
      repoURL: https://valkey.io/valkey-helm
      targetRevision: 0.9.4
      helm:
        releaseName: peertube-valkey
        valueFiles:
          - $values/argocd/peertube/valkey-values.yaml
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      path: argocd/peertube/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: peertube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
