apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- helmrepository-renovate-operator-repo.yaml
- helmrelease-renovate-operator.yaml
- externalsecret.yaml
- github-access-token.yaml
- onepassworditem.yaml
- renovatejob.yaml
