apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-github
  namespace: renovate-operator
spec:
  provider:
    name: github
  discoverTopics:
    - "renovate"
  extraEnv:
    - name: NODE_OPTIONS
      value: "--max-old-space-size=4096"
  image: renovate/renovate:43.104.3
  parallelism: 3
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 6Gi
  schedule: "0 * * * *"
  secretRef: renovate-secret
