tenant:
  name: minio-oky
  image: 
    image: quay.io/minio/minio
    tag: RELEASE.2024-11-07T00-52-20Z-cpuv1
  pools:
    name: pool-0
    storageClassName: oky-synology-01
    servers: 1
    volumesPerServer: 2