---
- name: create kubeadm-configure YAML file
  template:
    src: templates/kubeadm-config.yaml.j2
    dest: /home/{{ username }}/kubeadm-config.yaml
  when: "'k8s-cp-leader' in group_names"

- name: execute kubeadm init
  shell: kubeadm init --config "/home/{{ username }}/kubeadm-config.yaml" --upload-certs
  when: "'k8s-cp-leader' in group_names"

- name: create $HOME/.kube directory
  file:
    path: "/home/{{ username }}/.kube/"
    state: directory
    mode: '0755'
    owner: "{{ username }}"
    group: "{{ username }}"
  when: "'k8s-cp-leader' in group_names"

- name: create /root/.kube directory
  file:
    path: "/root/.kube/"
    state: directory
    mode: '0755'
    owner: "root"
    group: "root"
  when: "'k8s-cp-leader' in group_names"

- name: copy admin.conf to $HOME/.kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ username }}/.kube/config"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0600'
    remote_src: true
  when: "'k8s-cp-leader' in group_names"

- name: copy admin.conf to /root/.kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/root/.kube/config"
    owner: "root"
    group: "root"
    mode: '0600'
    remote_src: true
  when: "'k8s-cp-leader' in group_names"

- name: fetch kubeconfig
  fetch:
    src: /home/{{ username }}/.kube/config
    dest: "{{ lookup('env', 'HOME') }}/.kube/config"
    flat: yes
  when: "'k8s-cp-leader' in group_names"