- name: create kubeadm token
  shell: kubeadm token create --print-join-command
  register: create_token_result
  when: "'pke-oky-cp-leader' in group_names"

- name: set kubeadm token globally
  set_fact:
    kubernetes_join: "{{ create_token_result.stdout }}"
  run_once: true
  delegate_to: localhost

- name: get kubernetes ca key
  shell: kubeadm init phase upload-certs --upload-certs
  register: get_cert_key
  when: "'pke-oky-cp-leader' in group_names"

- name: set kubernetes ca key
  set_fact:
    cert_key: "{{ get_cert_key.stdout.split('\n')[-1] }}"
  run_once: true
  delegate_to: localhost

- name: Join kubeadm control plane
  command: >
    {{ kubernetes_join }}
    --control-plane
    --certificate-key {{ cert_key }}
  when: "'pke-oky-cp-follower' in group_names"
