vmselect:
  podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8481"

vminsert:
  podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8480"

vmstorage:
  persistentVolume:
    enabled: true
    size: 50Gi
    storageClassName: "oky-synology-01"
  podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8482"