apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kustomizations/cnpg.yaml
- kustomizations/cnpg-backup-config.yaml
- kustomizations/prometheus-operator-crd.yaml
- kustomizations/cert-manager.yaml
- kustomizations/cert-manager-config.yaml
- kustomizations/external-dns.yaml
- kustomizations/external-dns-config.yaml
- kustomizations/external-secrets.yaml
- kustomizations/kube-state-metrics.yaml
- kustomizations/longhorn.yaml
- kustomizations/longhorn-config.yaml
- kustomizations/misskey.yaml
- kustomizations/traefik.yaml
- kustomizations/navidrome.yaml
- kustomizations/registry.yaml
- kustomizations/spotify-nowplaying.yaml
- kustomizations/spotify-reblend.yaml
- kustomizations/sui.yaml
- kustomizations/summaly.yaml
- kustomizations/uptime-kuma.yaml
- kustomizations/grafana.yaml
- kustomizations/mimir.yaml
- kustomizations/loki.yaml
- kustomizations/alloy.yaml
