apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kustomizations/cnpg.yaml
- kustomizations/external-secrets-crds.yaml
- kustomizations/prometheus-operator-crd.yaml
- kustomizations/cert-manager.yaml
- kustomizations/daypassed-bot.yaml
- kustomizations/external-dns.yaml
- kustomizations/external-secrets.yaml
- kustomizations/kube-state-metrics.yaml
- kustomizations/mk-stream.yaml
- kustomizations/tailscale-operator.yaml
- kustomizations/traefik.yaml
- kustomizations/emoji-service.yaml
- kustomizations/navidrome.yaml
- kustomizations/note-tweet-connector.yaml
- kustomizations/registry.yaml
- kustomizations/renovate-operator.yaml
- kustomizations/rss-fetcher.yaml
- kustomizations/spotify-nowplaying.yaml
- kustomizations/spotify-reblend.yaml
- kustomizations/sui.yaml
- kustomizations/summaly.yaml
- kustomizations/uptime-kuma.yaml
- kustomizations/mc-mirror-cronjob.yaml
- kustomizations/prometheus-blackbox-exporter.yaml
- kustomizations/alloy.yaml
- kustomizations/blackbox-exporter-probes.yaml
