apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: kong-operator
      repoURL: https://charts.konghq.com
      targetRevision: 1.2.1
      helm:
        valueFiles:
          - $values/argocd/kong-operator/values.yaml
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kong-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
