apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rss-fetcher
  namespace: rss-fetcher
spec:
  interval: 10m
  releaseName: rss-fetcher
  targetNamespace: rss-fetcher
  install:
    createNamespace: false
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: rss-fetcher
      version: 0.3.1
      sourceRef:
        kind: HelmRepository
        name: rss-fetcher-repo
        namespace: rss-fetcher
      interval: 1h
  values:
    config:
      feeds:
      - name: "natsume-kurusu-yt"
        url: https://www.youtube.com/feeds/videos.xml?channel_id=UCRcLAVTbmx2-iNcXSsupdNA
      - name: "meruto-kuramochi-yt"
        url: https://www.youtube.com/feeds/videos.xml?channel_id=UCiA-trSZfB0i92V_-dyDqBw
      - name: "suzuna-nanase-yt"
        url: https://www.youtube.com/feeds/videos.xml?channel_id=UCtC3B1n4XMiJmrDtu1Ni5qw
      - name: "ui-shigure-yt"
        url: https://www.youtube.com/feeds/videos.xml?channel_id=UCt30jJgChL8qeT9VPadidSw
      - name: "alexandros-yt"
        url: https://www.youtube.com/feeds/videos.xml?channel_id=UCjIHV9sLF2yrYH2ClgPAzSg
      - name: "ichiro-yamaguchi-yt"
        url: https://www.youtube.com/feeds/videos.xml?channel_id=UCGQ4RBrN9wZJ1j6oOJ2KTFw
      interval: 30s
      existingSecret: rss-fetcher-webhooks
    externalValkey:
      host: rss-fetcher-valkey
      port: 6379
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    valkey:
      enabled: false
