apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: blackbox-exporter-probes-repo
  namespace: blackbox-exporter-probes
spec:
  interval: 1h
  url: https://soli0222.github.io/helm-charts
