apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vector
  namespace: vector
spec:
  interval: 10m
  releaseName: vector
  targetNamespace: vector
  install:
    createNamespace: false
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: vector
      version: 0.56.0
      sourceRef:
        kind: HelmRepository
        name: vector-repo
        namespace: vector
      interval: 1h
  values:
    role: Aggregator
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      ports:
      - name: syslog
        port: 1514
        protocol: UDP
        targetPort: 1514
    extraVolumes:
    - name: pke-natsume-mtls
      secret:
        secretName: pke-natsume-mtls
    extraVolumeMounts:
    - name: pke-natsume-mtls
      mountPath: /run/secrets/pke-natsume-mtls
      readOnly: true
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: true
        address: 127.0.0.1:8686
        playground: false
      sources:
        syslog:
          type: socket
          address: 0.0.0.0:1514
          mode: udp
          decoding:
            codec: bytes
      sinks:
        loki:
          type: loki
          inputs:
          - syslog
          endpoint: https://loki.pstr.space
          path: /loki/api/v1/push
          tenant_id: "fake"
          tls:
            crt_file: /run/secrets/pke-natsume-mtls/tls.crt
            key_file: /run/secrets/pke-natsume-mtls/tls.key
          encoding:
            codec: json
          labels:
            cluster: meruto
            source: syslog
            host: ix2215-1
