apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.data.storage.size }}
  storageClassName: {{ .Values.data.storageClassName }}