kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: navidrome-music-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.music.storage.size }}
  storageClassName: ""
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-music-pv
spec:
  capacity:
    storage: {{ .Values.music.storage.size }}
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
      - nfsvers=4.1
  nfs:
    server: {{ .Values.music.nfs.server }}
    path: {{ .Values.music.nfs.path }}