apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-cluster
  namespace: grafana
spec:
  instances: 2
  primaryUpdateMethod: switchover
  smartShutdownTimeout: 60
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: grafana
      owner: grafana
