apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-cluster
  namespace: grafana
spec:
  instances: 2
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: grafana-backup-store
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: grafana
      owner: grafana
