apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- helmrepository-grafana-repo.yaml
- onepassworditem.yaml
- onepassworditem-cnpg-backup.yaml
- cluster.yaml
- objectstore.yaml
- objectstore-restore.yaml
- scheduledbackup.yaml
- helmrelease-grafana.yaml
- podmonitor.yaml
