apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plane
  namespace: plane
spec:
  interval: 10m
  releaseName: plane
  targetNamespace: plane
  install:
    createNamespace: false
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: plane-ce
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: plane-charts-repo
        namespace: plane
      interval: 1h
  values:
    planeVersion: v1.2.3

    ingress:
      enabled: true
      type: traefik
      host: plane.pstr.space
      annotations:
        kubernetes.io/ingress.class: traefik
        external-dns.alpha.kubernetes.io/target: natsume.pstr.space
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      admin:
        enabled: true
        middlewares:
        - name: plane-admin-basic-auth
          namespace: plane
      tls:
        enabled: true
        secretName: plane.pstr.space-http01
        createCertificate: true
        issuerRef:
          kind: ClusterIssuer
          name: letsencrypt-http01

    env:
      web_url: https://plane.pstr.space

    appSecrets:
      secretKeyFrom:
        secretKeyRef:
          name: plane-app-env
          key: SECRET_KEY
      liveServerSecretKeyFrom:
        secretKeyRef:
          name: plane-app-env
          key: SECRET_KEY

    postgres:
      mode: externalUrlRef
      urlFrom:
        secretKeyRef:
          name: plane-cluster-app
          key: uri

    redis:
      mode: externalUrl
      url: redis://plane-valkey:6379/0
      local_setup: false

    rabbitmq:
      local_setup: true
      volumeSize: 1Gi

    minio:
      local_setup: false

    objectStorage:
      provider: s3
      useMinio: false
      bucket: plane-uploads
      region: auto
      fileSizeLimit: "5242880"
      endpointUrlFrom:
        secretKeyRef:
          name: plane-app-env
          key: AWS_S3_ENDPOINT_URL
      accessKeyIdFrom:
        secretKeyRef:
          name: plane-app-env
          key: AWS_ACCESS_KEY_ID
      secretAccessKeyFrom:
        secretKeyRef:
          name: plane-app-env
          key: AWS_SECRET_ACCESS_KEY

    migrator:
      strategy: managedJob

    web: &smallFrontend
      memoryLimit: 512Mi
      cpuLimit: 500m
      cpuRequest: 50m
      memoryRequest: 64Mi
    space: *smallFrontend
    admin: *smallFrontend
    live: *smallFrontend

    api: &smallBackend
      memoryLimit: 512Mi
      cpuLimit: 500m
      cpuRequest: 100m
      memoryRequest: 128Mi
    worker:
      memoryLimit: 1Gi
      cpuLimit: 500m
      cpuRequest: 100m
      memoryRequest: 256Mi
    beatworker:
      memoryLimit: 256Mi
      cpuLimit: 250m
      cpuRequest: 50m
      memoryRequest: 64Mi
