apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- onepassworditem.yaml
- onepassworditem-admin-basic-auth.yaml
- onepassworditem-cnpg-backup.yaml
- helmrepository-plane-charts-repo.yaml
- helmrepository-valkey-repo.yaml
- cluster.yaml
- middleware-admin-basic-auth.yaml
- helmrelease-plane-valkey.yaml
- helmrelease-plane.yaml
- cronjob-pg-dump.yaml
