apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: emoji-bot-gateway-repo-2
  namespace: emoji-service
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/soli0222/charts
