---
- name: Deploy etcd maintenance script
  ansible.builtin.template:
    src: etcd-maintenance.sh.j2
    dest: /usr/local/sbin/etcd-maintenance.sh
    owner: root
    group: root
    mode: "0750"

- name: Deploy etcd maintenance service
  ansible.builtin.template:
    src: etcd-maintenance.service.j2
    dest: /etc/systemd/system/etcd-maintenance.service
    owner: root
    group: root
    mode: "0644"

- name: Deploy etcd maintenance timer
  ansible.builtin.template:
    src: etcd-maintenance.timer.j2
    dest: /etc/systemd/system/etcd-maintenance.timer
    owner: root
    group: root
    mode: "0644"

- name: Enable and start etcd maintenance timer
  ansible.builtin.systemd:
    name: etcd-maintenance.timer
    enabled: true
    state: started
    daemon_reload: true

