apiVersion: v1
kind: Service
metadata:
  name: alloy-otlp
  namespace: alloy
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/instance: alloy
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: otlp-grpc
    protocol: TCP
    appProtocol: grpc
  - name: otlp-http
    port: 4318
    targetPort: otlp-http
    protocol: TCP
