---
general_configuration_timezone: Asia/Tokyo

general_configuration_apt_cache_valid_time: 3600

general_configuration_packages:
  - ca-certificates
  - conntrack
  - curl
  - dnsutils
  - gnupg
  - iptables
  - iproute2
  - iputils-ping
  - jq
  - lsb-release
  - openssl
  - socat
  - unzip
  - vim

general_configuration_chrony_packages:
  - chrony

general_configuration_chrony_servers:
  - ntp1.jst.mfeed.ad.jp
  - ntp2.jst.mfeed.ad.jp
  - ntp3.jst.mfeed.ad.jp
  - ntp1.v6.mfeed.ad.jp 
  - ntp2.v6.mfeed.ad.jp
  - ntp3.v6.mfeed.ad.jp

general_configuration_chrony_allow_networks: []

general_configuration_disable_swap: true
general_configuration_mask_swap_units: false
general_configuration_swap_files:
  - /swap.img

general_configuration_journald_max_use: 1G
general_configuration_journald_max_file_sec: 1month
