apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- helmrepository-prometheus-community-repo.yaml
- helmrelease-ccat-snmp-exporter.yaml
- onepassworditem.yaml
