apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: spn-cluster
  namespace: spotify-nowplaying
spec:
  instances: 2
  primaryUpdateMethod: switchover
  smartShutdownTimeout: 60
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: spn
      owner: spn
