apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: spotify-nowplaying-repo
  namespace: spotify-nowplaying
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/soli0222/charts
