apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- helmrepository-spotify-nowplaying-repo.yaml
- helmrelease-spotify-nowplaying.yaml
- cluster.yaml
- onepassworditem.yaml
- objectstore.yaml
- scheduledbackup.yaml
- onepassworditem-cnpg-backup.yaml
- podmonitor.yaml
