apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: spn-backup-store
  namespace: spotify-nowplaying
spec:
  retentionPolicy: 30d
  configuration:
    destinationPath: s3://cnpg-backup/
    endpointURL: ${CNPG_BACKUP_ENDPOINT_URL}
    s3Credentials:
      accessKeyId:
        name: cnpg-backup-s3-secret
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-backup-s3-secret
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
      maxParallel: 4
    data:
      compression: gzip
