---
- name: Update apt cache (equivalent to apt-get update)
  ansible.builtin.apt:
    update_cache: yes

- name: Install Keepalived
  ansible.builtin.apt:
    name:
      - keepalived
    state: present

- name: Ensure keepalived conf is set  
  template: >
    src=templates/keepalived-lb-1.conf.j2
    dest=/etc/keepalived/keepalived.conf
  when: inventory_hostname == 'pke-oky-lb-1'

- name: Ensure keepalived conf is set
  template: >
    src=templates/keepalived-lb-2.conf.j2
    dest=/etc/keepalived/keepalived.conf
  when: inventory_hostname == 'pke-oky-lb-2'

- name: Ensure keepalived sh is set
  template: >
    src=templates/check_apiserver.sh.j2
    dest=/etc/keepalived/check_apiserver.sh  

- name: Ensure keepalived is started
  service: > 
    name=keepalived
    state=started
    enabled=yes

- name: Restart Keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted
    enabled: yes