apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: renovate-operator
      repoURL: https://helm.mogenius.com/public
      targetRevision: 4.0.0
      helm:
        releaseName: renovate-operator
        valueFiles:
          - $values/argocd/renovate-operator/values.yaml
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      path: argocd/renovate-operator/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: renovate-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
