apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- helmrepository-rss-fetcher-repo.yaml
- helmrelease-rss-fetcher.yaml
- helmrepository-valkey-repo-2.yaml
- helmrelease-rss-fetcher-valkey.yaml
- onepassworditem.yaml
