apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: pke-natsume-mtls-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pke-natsume-mtls-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: pke-natsume-mtls-ca
  secretName: pke-natsume-mtls-ca-secret
  duration: 87600h # 10 years
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: pke-natsume-mtls-selfsigned
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: pke-natsume-mtls-ca-issuer
spec:
  ca:
    secretName: pke-natsume-mtls-ca-secret
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: pke-natsume-mtls
  namespace: cert-manager
spec:
  clientAuth:
    secretNames:
      - pke-natsume-mtls-ca-secret
    clientAuthType: RequireAndVerifyClientCert
