apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pke-natsume-mtls-client
  namespace: cert-manager
spec:
  commonName: pke-natsume-client
  secretName: pke-natsume-mtls-client-secret
  duration: 43800h # 5 year
  renewBefore: 720h # 30 days
  usages:
    - client auth
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: pke-natsume-mtls-ca-issuer
    kind: ClusterIssuer
