apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-operator-crd
  namespace: flux-system
spec:
  interval: 10m
  path: "./flux/clusters/meruto/apps/prometheus-operator-crd"
  prune: true
  wait: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
