apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frpc
  namespace: frpc
spec:
  selector:
    matchLabels:
      app: frpc
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
