---
- name: Update apt cache
  become: yes  
  apt:
    update_cache: yes

- name: Install required packages
  become: yes  
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create Docker keyrings directory
  become: yes  
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker's official GPG key
  become: yes  
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository to Apt sources
  become: yes  
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    executable: /bin/bash

- name: Update apt cache after adding Docker repository
  become: yes  
  apt:
    update_cache: yes

- name: Install containerd.io
  become: yes  
  apt:
    name: containerd.io
    state: present

- name: Generate containerd default configuration
  become: yes  
  command: containerd config default
  register: containerd_default_config

- name: Write containerd configuration to file
  become: yes  
  copy:
    content: "{{ containerd_default_config.stdout }}"
    dest: /etc/containerd/config.toml

- name: Enable SystemdCgroup in containerd configuration
  become: yes  
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^SystemdCgroup = false'
    line: 'SystemdCgroup = true'

- name: Restart containerd service
  become: yes  
  systemd:
    name: containerd
    state: restarted
    enabled: true
