apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sui-cluster-restored
  namespace: sui
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.6-system-trixie
  primaryUpdateMethod: switchover
  smartShutdownTimeout: 60
  affinity:
    nodeSelector:
      kubernetes.io/hostname: natsume-08
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: sui-backup-store
  storage:
    storageClass: topolvm
    size: 5Gi
    resizeInUseVolumes: false
  bootstrap:
    recovery:
      source: origin
      database: sui
      owner: sui
      recoveryTarget:
        backupID: 20261003T181500
  externalClusters:
  - name: origin
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: sui-backup-store-restore
        serverName: sui-cluster
