apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sui-cluster
  namespace: sui
spec:
  instances: 1
  primaryUpdateMethod: switchover
  smartShutdownTimeout: 60
  affinity:
    nodeSelector:
      kubernetes.io/hostname: natsume-08
  storage:
    storageClass: topolvm
    size: 5Gi
    resizeInUseVolumes: false
  bootstrap:
    initdb:
      database: sui
      owner: sui
