apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: distribution
  namespace: registry
spec:
  interval: 10m
  releaseName: distribution
  targetNamespace: registry
  install:
    createNamespace: false
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: distribution
      version: 0.1.2
      sourceRef:
        kind: HelmRepository
        name: distribution-repo
        namespace: registry
      interval: 1h
  values:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
    persistence:
      enabled: false
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-http01
        traefik.ingress.kubernetes.io/router.tls.options: cert-manager-pke-natsume-mtls@kubernetescrd
      hosts:
      - host: registry.str08.net
        paths:
        - path: "/"
          pathType: Prefix
      tls:
      - secretName: registry.str08.net-http01
        hosts:
        - registry.str08.net
    env:
      - name: REGISTRY_STORAGE_S3_REGIONENDPOINT
        valueFrom:
          secretKeyRef:
            name: registry-s3-credentials
            key: s3-endpoint
    config:
      storage:
        s3:
          region: APAC
          bucket: registry-str08-net
          chunksize: 16777216
          multipartcopychunksize: 16777216
          multipartcopythresholdsize: 16777216
        cache:
          blobdescriptor: redis
        maintenance:
          uploadpurging:
            enabled: true
            age: 168h
            interval: 72h
          readonly:
            enabled: false
        redirect:
          disable: false
      redis:
        addrs:
        - registry-valkey:6379
    secrets:
      existingSecret: registry-s3-credentials
    serviceMonitor:
      enabled: true
