apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- helmrepository-distribution-repo.yaml
- helmrelease-distribution.yaml
- helmrepository-valkey-repo-2.yaml
- helmrelease-registry-valkey.yaml
- onepassworditem.yaml
