env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: apiToken

sources:
  - service
  - ingress
  - crd
  - traefik-proxy

domainFilters: 
  - str08.net

provider:
  name: cloudflare

extraArgs: 
  - --traefik-disable-legacy
  - --txt-new-format-only
