- name: Update apt cache (equivalent to apt-get update)
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - nfs-common
      - language-pack-ja-base
      - language-pack-ja
      - ibus-mozc
    state: present