apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oky-synology-01
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      path: argocd/oky-synology-01/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: oky-synology-01
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
