apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: signal-syscalls
spec:
  options:
  - name: policy-mode
    value: monitor
  tracepoints:
  - subsystem: signal
    event: signal_generate
    raw: true
    message: "SIGHUP generated"
    tags:
    - signal
    - sighup
    args:
    - index: 0
      type: int
      label: sig
    - index: 2
      type: int
      resolve: pid
      label: target_pid
    - index: 3
      type: int
      label: group
    - index: 4
      type: int
      label: result
    selectors:
    - matchArgs:
      - index: 0
        operator: Equal
        values:
        - "1"
      matchActions:
      - action: Post
  - subsystem: signal
    event: signal_deliver
    raw: true
    message: "SIGHUP delivered"
    tags:
    - signal
    - sighup
    args:
    - index: 0
      type: int
      label: sig
    selectors:
    - matchArgs:
      - index: 0
        operator: Equal
        values:
        - "1"
      matchActions:
      - action: Post
  kprobes:
  - call: sys_kill
    syscall: true
    message: "SIGHUP syscall observed"
    tags:
    - signal
    - sighup
    args:
    - index: 0
      type: int
      label: pid
    - index: 1
      type: int
      label: sig
    selectors:
    - matchArgs:
      - index: 1
        operator: Equal
        values:
        - "1"
      matchActions:
      - action: Post
  - call: sys_tkill
    syscall: true
    message: "SIGHUP syscall observed"
    tags:
    - signal
    - sighup
    args:
    - index: 0
      type: int
      label: tid
    - index: 1
      type: int
      label: sig
    selectors:
    - matchArgs:
      - index: 1
        operator: Equal
        values:
        - "1"
      matchActions:
      - action: Post
  - call: sys_tgkill
    syscall: true
    message: "SIGHUP syscall observed"
    tags:
    - signal
    - sighup
    args:
    - index: 0
      type: int
      label: tgid
    - index: 1
      type: int
      label: tid
    - index: 2
      type: int
      label: sig
    selectors:
    - matchArgs:
      - index: 2
        operator: Equal
        values:
        - "1"
      matchActions:
      - action: Post
  - call: sys_pidfd_send_signal
    syscall: true
    message: "SIGHUP syscall observed"
    tags:
    - signal
    - sighup
    args:
    - index: 0
      type: int
      label: pidfd
    - index: 1
      type: int
      label: sig
    selectors:
    - matchArgs:
      - index: 1
        operator: Equal
        values:
        - "1"
      matchActions:
      - action: Post
