apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: reblend-cluster
  namespace: spotify-reblend
spec:
  instances: 2
  primaryUpdateMethod: switchover
  smartShutdownTimeout: 60
  affinity:
    nodeSelector:
      kubernetes.io/hostname: natsume-08
  storage:
    storageClass: topolvm
    size: 5Gi
    resizeInUseVolumes: false
  bootstrap:
    initdb:
      database: reblend
      owner: reblend
