apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: reblend-cluster
  namespace: spotify-reblend
spec:
  instances: 2
  primaryUpdateMethod: switchover
  smartShutdownTimeout: 60
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: reblend
      owner: reblend
