apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: oky-synology-01
  namespace: oky-synology-01
  labels:
    app: oky-synology-01
    kubernetes.io/service-name: oky-synology-01
addressType: IPv4
ports:
  - name: metrics
    port: 9116
    protocol: TCP
endpoints:
  - addresses:
      - 192.168.20.250
