apiVersion: v1
kind: Endpoints
metadata:
  name: oky-synology-01
  namespace: oky-synology-01
  labels:
    app: oky-synology-01
subsets:
  - addresses:
      - ip: 192.168.20.250
    ports:
      - name: metrics
        port: 9116
        protocol: TCP
