apiVersion: v1
kind: Service
metadata:
  name: oky-synology-01
  namespace: oky-synology-01
  labels:
    app: oky-synology-01
spec:
  ports:
    - name: metrics
      port: 9116
      protocol: TCP
      targetPort: 9116
