apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: oky-synology-01
  namespace: oky-synology-01
spec:
  selector:
    matchLabels:
      app: oky-synology-01
  endpoints:
    - port: metrics
      path: /snmp
      interval: 30s
      scrapeTimeout: 30s
      params:
        target:
          - 192.168.20.250
        module:
          - synology
        auth:
          - public_v3
