---
ansible_host: natsume-04

network_netplan:
  global:
    device: ens3
    ipv4: 133.18.140.50/23
    ipv6:
      - 2406:8c00:0:3464:133:18:140:50/64
    default_route:
      - 133.18.140.1
      - via: 2406:8c00:0:3464::1
        on-link: true
    nameservers:
      - 1.1.1.1
      - 1.0.0.1
      - 2606:4700:4700::1111
      - 2606:4700:4700::1001
    routes: []

  private:
    device: ens7
    ipv4:
      - 192.168.9.4/24
    ipv6:
      - fd00:192:168:9::4/64
    default_route: []
    nameservers: []
    routes: []
