---
ansible_host: natsume-05

longhorn_storage_devices:
  - /dev/vda4

network_netplan:
  global:
    device: ens3
    ipv4: TBD
    ipv6:
      - TBD
    default_route:
      - TBD
      - via: TBD
        on-link: true
    nameservers:
      - 1.1.1.1
      - 1.0.0.1
      - 2606:4700:4700::1111
      - 2606:4700:4700::1001
    routes: []

  private:
    device: ens7
    ipv4:
      - 192.168.9.5/24
    ipv6:
      - fd00:192:168:9::5/64
    default_route: []
    nameservers: []
    routes: []
