apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch-deployment
  labels:
    app: meilisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:{{ .Values.image.tag }}
          ports:
            - containerPort: 7700
          env:
            - name: MEILI_NO_ANALYTICS
              value: "{{ .Values.env.MEILI_NO_ANALYTICS }}"
            - name: MEILI_ENV
              value: "{{ .Values.env.MEILI_ENV }}"
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: meilisearch-secret
                  key: MEILI_MASTER_KEY
          volumeMounts:
            - mountPath: /meili_data
              name: meilisearch-pvc
      volumes:
        - name: meilisearch-pvc
          persistentVolumeClaim:
            claimName: meilisearch-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch-service
spec:
  selector:
    app: meilisearch
  ports:
    - protocol: TCP
      port: 7700
      targetPort: 7700
  type: ClusterIP