global:
  extraArgs:
    - -config.expand-env=true
  envFrom:
    - name: MINIO_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: loki-minio
          key: accesskey
    - name: MINIO_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: loki-minio
          key: secretkey

loki:
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    aws:
      region: minio-oky-1
      bucketnames: loki-chunk
      s3forcepathstyle: false
  pattern_ingester:
      enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 672h # 28 days retention

  storage:
    type: s3
    bucketNames:
        chunks: loki-chunk
        ruler: loki-ruler
        admin: loki-admin
    s3:
      endpoint: "minio-oky-hl.minio-tenant:9000"
      region: "minio-oky-1"
      secretAccessKey: "${MINIO_SECRET_ACCESS_KEY}"
      accessKeyId: "${MINIO_ACCESS_KEY_ID}"
      s3ForcePathStyle: true

minio:
  enabled: false

deploymentMode: SingleBinary

chunksCache:
  allocatedMemory: 1024

singleBinary:
  replicas: 3
  persistence:
    storageClass: oky-synology-02-nfs
    accessModes:
      - ReadWriteOnce
    size: 30Gi

# Zero out replica counts of other deployment modes
backend:
  replicas: 0

read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0