persistence:
  type: pvc
  enabled: true
  storageClassName: oky-synology-01-nfs
  accessModes:
    - ReadWriteOnce
  size: 10Gi

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - grafana.oky.pke.str08.net
  tls:
   - secretName: grafana.oky.pke.str08.net-dns01
     hosts:
       - grafana.oky.pke.str08.net