logs:
  access:
    enabled: true

service:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "traefik.oky.pke.str08.net"

ingressClass:
  enabled: true
  isDefaultClass: true
  name: "traefik"

providers:
  kubernetesCRD:
    ingressClass: "traefik"

  kubernetesIngress:
    ingressClass:  "traefik"

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.oky.pke.str08.net`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    entryPoints: ["web", "websecure"]
    tls: 
      secretName: "traefik.oky.pke.str08.net-dns01"