ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.oky.pke.str08.net`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    entryPoints: ["web", "websecure"]
    tls: 
      secretName: "traefik.oky.pke.str08.net-dns01"