---
- name: All VM Config
  hosts: pke-oky-vm
  roles:
    - 01-all-vm-config

- name: Install HAProxy
  hosts: pke-oky-lb
  roles:
    - 02-install-haproxy

- name: Install Keepalived
  hosts: pke-oky-lb
  roles:
    - 03-install-keepalived

- name: Set Config
  hosts: pke-oky-k8s
  roles:
    - 04-set-config

- name: Install Containerd
  hosts: pke-oky-k8s
  roles:
    - 05-install-containerd

- name: Install Kubernetes
  hosts: pke-oky-k8s
  roles:
    - 06-install-kubernetes