---
- name: Precheck etcd before upgrade
  hosts: etcd
  become: true
  roles:
    - etcd-precheck

- name: Upgrade external etcd
  hosts: etcd
  become: true
  serial: 1
  roles:
    - upgrade-etcd

- name: Validate etcd after upgrade
  hosts: etcd
  become: true
  roles:
    - etcd-precheck
