---
etcd_version: "3.6.11"
etcd_data_dir: /var/lib/etcd
etcd_download_dir: /var/lib/etcd/downloads
etcd_snapshot_dir: /var/lib/etcd/snapshots
etcd_pki_dir: /etc/etcd/pki
etcd_initial_cluster_token: pke-etcd
etcd_cluster_state: new
etcd_snapshot_retention_days: 7
etcd_maintenance_on_calendar: "*-*-* 00/6:00:00"

