---
k3s_node_role: server
k3s_datastore_cafile: /etc/etcd/pki/ca.crt
k3s_datastore_certfile: /etc/etcd/pki/k3s-etcd-client.crt
k3s_datastore_keyfile: /etc/etcd/pki/k3s-etcd-client.key
k3s_datastore_endpoint: >-
  {{
    groups['etcd']
    | map('extract', hostvars, 'ansible_host')
    | map('regex_replace', '^(.*)$', 'https://\\1:2379')
    | join(',')
  }}
