# Monitoring Configuration
monitoring_domain: oky.pke.str08.net

# VictoriaMetrics Configuration
victoriametrics_endpoint: "https://vminsert.{{ monitoring_domain }}/insert/0/prometheus/"

# Loki Configuration  
loki_endpoint: "https://loki-gateway.{{ monitoring_domain }}/loki/api/v1/push"

# Alloy Configuration
alloy_disable_reporting: true
