apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: note-tweet-connector-repo
  namespace: note-tweet-connector
spec:
  interval: 1h
  url: https://soli0222.github.io/helm-charts
