apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- helmrepository-misskey-repo.yaml
- helmrepository-valkey-repo.yaml
- helmrelease-misskey-valkey.yaml
- cluster.yaml
- objectstore.yaml
- scheduledbackup.yaml
- onepassworditem-cnpg-backup.yaml
- helmrelease-misskey.yaml
