---
# Handlers for install-containerd role

- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart containerd
  become: true
  ansible.builtin.systemd:
    name: containerd
    state: restarted
