webui:
  enabled: true
  disableauth: true

  ingress:
    enabled: true
    ingressClassName: "traefik"
    annotations: 
      cert-manager.io/cluster-issuer: "letsencrypt"
    hosts:
      - host: falco.oky.pke.str08.net
        paths:
        - path: /
    tls:
      - secretName: falco.oky.pke.str08.net-dns01
        hosts:
          - falco.oky.pke.str08.net