---
- name: Update apt cache (equivalent to apt-get update)
  apt:
    update_cache: yes

- name: Install Keepalived
  apt:
    name:
      - keepalived
    state: present

- name: Ensure keepalived conf is set  
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived

- name: Ensure keepalived sh is set
  template:
    src: check_apiserver.sh.j2
    dest: /etc/keepalived/check_apiserver.sh
    mode: '0755'
  notify: restart keepalived  

- name: Ensure keepalived is started
  service: 
    name: keepalived
    state: started
    enabled: yes