- name: create kubeadm token
  shell: kubeadm token create --print-join-command
  register: create_token_result
  when: "'k8s-cp-leader' in group_names"

- name: set kubeadm token globally
  set_fact:
    kubernetes_join: "{{ create_token_result.stdout }}"
  run_once: true
  delegate_to: localhost

- name: get kubernetes ca key
  shell: kubeadm init phase upload-certs --upload-certs
  register: get_cert_key
  when: "'k8s-cp-leader' in group_names"

- name: join kubeadm worker
  command: >
    {{ kubernetes_join }}
  when: "'k8s-wk' in group_names"
