- name: create kubeadm token
  shell: kubeadm token create --print-join-command
  register: create_token_result
  run_once: true
  delegate_to: "{{ groups['k8s-cp-leader'][0] }}"

- name: set kubeadm token globally
  set_fact:
    kubernetes_join: "{{ create_token_result.stdout }}"
  run_once: true
  delegate_to: localhost

- name: join kubeadm worker
  command: >
    {{ kubernetes_join }}
  when: "'k8s-wk' in group_names"
