apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: ntfy-admin
  namespace: ntfy
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  # auth-users field に <username>:<bcrypt password hash>:admin を保存する。
  itemPath: vaults/Kubernetes/items/ntfy-admin
