apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kustomizations/alloy.yaml
- kustomizations/prometheus-operator-crd.yaml
- kustomizations/blackbox-exporter-probes.yaml
- kustomizations/cert-manager.yaml
- kustomizations/cert-manager-config.yaml
- kustomizations/cloudflare-tunnel-ingress-controller.yaml
- kustomizations/cnpg.yaml
- kustomizations/external-dns.yaml
- kustomizations/ix2215-snmp-exporter.yaml
- kustomizations/kube-state-metrics.yaml
- kustomizations/longhorn.yaml
- kustomizations/longhorn-config.yaml
- kustomizations/navidrome.yaml
- kustomizations/prometheus-blackbox-exporter.yaml
- kustomizations/tetragon.yaml
- kustomizations/tetragon-policies.yaml
- kustomizations/traefik.yaml
- kustomizations/vector.yaml
