apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- helmrepository-cloudflare-tunnel-ingress-controller-repo.yaml
- onepassworditem.yaml
- helmrelease-cloudflare-tunnel-ingress-controller.yaml

