apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflared-pke-meruto
  namespace: cloudflare-tunnel-ingress-controller
spec:
  itemPath: "vaults/Kubernetes/items/cloudflared-pke-meruto"

