apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-kkg
  namespace: minio-tenant
spec:
  selector: {}
  namespaceSelector:
    matchNames:
      - minio-tenant
  endpoints:
    - port: http-minio
      path: /minio/v2/metrics/cluster
      interval: 30s
      scheme: http
    - port: http-minio
      path: /minio/v2/metrics/node
      interval: 30s
      scheme: http
    - port: http-minio
      path: /minio/v2/metrics/bucket
      interval: 30s
      scheme: http
    - port: http-minio
      path: /minio/v2/metrics/resource
      interval: 30s
      scheme: http
